export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_USER = "CLEAR_USER";
export const GET_FILTERED_USERTYPE = "GET_FILTERED_USERTYPE";
export const SET_ALERT = " SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const GET_USERS = "GET_USERS";
export const EMAIL_SENT = "EMAIL_SENT";

export const ADD_RESULT = "ADD_RESULT";
export const ERROR_RESULT = "ERROR_RESULT";

export const CLEAR_FILTER = "CLEAR_FILTER";

export const GET_ERRORS = "GET_ERRORS";
export const LOAD_QUIZ = "LOAD_QUIZ";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_QUIZ_LOADING = "SET_QUIZ_LOADING";
export const END_FREE_QUIZ = "END_FREE_QUIZ";
export const CLEAR_QUIZ_STATS = "CLEAR_QUIZ_STATS";
export const SET_USER_COLOR = "SET_USER_COLOR";

export const GET_PROJECT = "GET_PROJECT";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECT_ERROR = "PROJECT_ERROR";
export const CLEAR_PROJECT = "CLEAR_PROJECT";
export const FILTER_PROJECT = "FILTER_PROJECT";

export const GET_INVESTMENT = "GET_INVESTMENT";
export const GET_USERS_INVESTMENTS = "GET_USERS_INVESTMENTS";
export const SET_CURRENT_INVESTMENT = "SET_CURRENT_INVESTMENT";
export const GET_INVESTMENTS = "GET_INVESTMENTS";
export const GET_GUEST_DONATIONS = "GET_GUEST_DONATIONS";
export const GET_CURRENCIES = "GET_CURRENCIES";
export const ADD_INVESTMENT = "ADD_INVESTMENT";
export const FETCH_INVESTMENT = "FETCH_INVESTMENT";
export const EDIT_INVESTMENT = "EDIT_INVESTMENT";
export const DELETE_INVESTMENT = "DELETE_INVESTMENT";
export const INVESTMENT_ERROR = "INVESTMENT_ERROR";
export const CLEAR_INVESTMENT = "CLEAR_INVESTMENT";
export const FILTER_INVESTMENT = "FILTER_INVESTMENT";
export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_FAILURE = "ADD_IMAGE_FAILURE";

export const GET_EXPENSE = "GET_EXPENSE";
export const SET_CURRENT_EXPENSE = "SET_CURRENT_EXPENSE";
export const GET_USERS_EXPENSES = "GET_USERS_EXPENSES";
export const GET_EXPENSES = "GET_EXPENSES";
export const GET_GUEST_EXPENSES = "GET_GUEST_EXPENSES";

export const ADD_EXPENSE = "ADD_EXPENSE";
export const FETCH_EXPENSE = "FETCH_EXPENSE";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const EXPENSE_ERROR = "EXPENSE_ERROR";
export const CLEAR_EXPENSE = "CLEAR_EXPENSE";
export const FILTER_EXPENSE = "FILTER_EXPENSE";

export const GET_CUSTOMER_PAY = "GET_CUSTOMER_PAY";
export const SET_CURRENT_CUSTOMER_PAY = "SET_CURRENT_CUSTOMER_PAY";
export const GET_CUSTOMER_PAYS = "GET_CUSTOMER_PAYS";
export const FETCH_CUSTOMERPAY = "FETCH_CUSTOMERPAY";

export const CUSTOMER_BASED_PAY = "CUSTOMER_BASED_PAY";
export const ADD_CUSTOMER_PAY = "ADD_CUSTOMER_PAY";
export const EDIT_CUSTOMER_PAY = "EDIT_CUSTOMER_PAY";
export const DELETE_CUSTOMER_PAY = "DELETE_CUSTOMER_PAY";
export const CUSTOMER_PAY_ERROR = "CUSTOMER_PAY_ERROR";
export const CLEAR_CUSTOMER_PAY = "CLEAR_CUSTOMER_PAY";
export const FILTER_CUSTOMER_PAY = "FILTER_CUSTOMER_PAY";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const CLEAR_CUSTOMER = "CLEAR_CUSTOMER";
export const FILTER_CUSTOMER = "FILTER_CUSTOMER";

export const GET_RATION = "GET_RATION";
export const SET_CURRENT_RATION = "SET_CURRENT_RATION";
export const GET_RATIONS = "GET_RATIONS";
export const ADD_RATION = "ADD_RATION";
export const EDIT_RATION = "EDIT_RATION";
export const DELETE_RATION = "DELETE_RATION";
export const RATION_ERROR = "RATION_ERROR";
export const CLEAR_RATION = "CLEAR_RATION";
export const FILTER_RATION = "FILTER_RATION";
export const GET_TOTAL_RATION = "GET_TOTAL_RATION";
export const SEARCH_DELIVERY = "SEARCH_DELIVERY";
// REPORTS

export const GET_ALL_CUSTOMER_PAYS = "GET_ALL_CUSTOMER_PAYS";
export const GET_ALL_EXPENSES = "GET_ALL_EXPENSES";
export const GET_ALL_INVESTMENTS = "GET_ALL_INVESTMENTS";
export const OVER_ALL_SUM_INV = "OVER_ALL_SUM_INV";
export const OVER_ALL_SUM_EXP = "OVER_ALL_SUM_EXP";
export const OVER_ALL_SUM_CUSTPAY = "OVER_ALL_SUM_CUSTPAY";

export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const GET_ALL_RATIONS = "GET_ALL_RATIONS";
export const GET_PROJECTWISE_INVESTMENTS = "GET_PROJECTWISE_INVESTMENTS";
export const GET_TOTALWISE_INVESTMENTS = "GET_TOTALWISE_INVESTMENTS";
export const GET_TOTALWISE_EXPENSES = "GET_TOTALWISE_EXPENSES";
export const GET_PROJECTWISE_EXPENSES = "GET_PROJECTWISE_EXPENSES";
export const GET_PROJECTWISE_CUSTPAY = "GET_PROJECTWISE_CUSTPAY";
export const GET_TOTALWISE_CUSTPAY = "GET_TOTALWISE_CUSTPAY";
export const GET_USERS_SUM_INVESTMENTS = "GET_USERS_SUM_INVESTMENTS";
export const GET_USERS_SUM_EXPENSES = "GET_USERS_SUM_EXPENSES";
export const CUST_SUM_PAYMENT = "CUST_SUM_PAYMENT";

export const GET_MONTHLY_INVESTMENTS = "GET_MONTHLY_INVESTMENTS";
export const GET_MONTHLY_EXPENSES = "GET_MONTHLY_EXPENSES";
export const GET_MONTHLY_CUSTPAY = "GET_MONTHLY_CUSTPAY";

export const GET_USER_MONTHLY_INVESTMENTS = "GET_USER_MONTHLY_INVESTMENTS";
export const GET_USER_MONTHLY_EXPENSES = "GET_USER_MONTHLY_EXPENSES";
export const GET_USER_MONTHLY_CUSTPAY = "GET_USER_MONTHLY_CUSTPAY";

export const GET_ACC_PAY = "GET_ACC_PAY";
export const SET_CURRENT_ACC_PAY = "SET_CURRENT_ACC_PAY";
export const GET_ACC_PAYS = "GET_ACC_PAYS";
export const ADD_ACC_PAY = "ADD_ACC_PAY";
export const EDIT_ACC_PAY = "EDIT_ACC_PAY";
export const DELETE_ACC_PAY = "DELETE_ACC_PAY";
export const ACC_PAY_ERROR = "ACC_PAY_ERROR";
export const CLEAR_ACC_PAY = "CLEAR_ACC_PAY";
export const FILTER_ACC_PAY = "FILTER_ACC_PAY";
export const GET_ALL_ACC_PAYS = "GET_ALL_ACC_PAYS";

export const GET_UPI_PAY = "GET_UPI_PAY";
export const SET_CURRENT_UPI_PAY = "SET_CURRENT_UPI_PAY";
export const GET_UPI_PAYS = "GET_UPI_PAYS";
export const ADD_UPI_PAY = "ADD_UPI_PAY";
export const EDIT_UPI_PAY = "EDIT_UPI_PAY";
export const DELETE_UPI_PAY = "DELETE_UPI_PAY";
export const UPI_PAY_ERROR = "UPI_PAY_ERROR";
export const CLEAR_UPI_PAY = "CLEAR_UPI_PAY";
export const FILTER_UPI_PAY = "FILTER_UPI_PAY";
export const GET_ALL_UPI_PAYS = "GET_ALL_UPI_PAYS";

export const GET_WHAT_GROUP = "GET_WHAT_GROUP";
export const SET_CURRENT_WHAT_GROUP = "SET_CURRENT_WHAT_GROUP";
export const GET_WHAT_GROUPS = "GET_WHAT_GROUPS";
export const ADD_WHAT_GROUP = "ADD_WHAT_GROUP";
export const EDIT_WHAT_GROUP = "EDIT_WHAT_GROUP";
export const DELETE_WHAT_GROUP = "DELETE_WHAT_GROUP";
export const WHAT_GROUP_ERROR = "WHAT_GROUP_ERROR";
export const CLEAR_WHAT_GROUP = "CLEAR_WHAT_GROUP";
export const FILTER_WHAT_GROUP = "FILTER_WHAT_GROUP";
export const GET_TOTAL_WHAT_GROUP = "GET_TOTAL_WHAT_GROUP";

export const GET_SETTING = "GET_SETTING";
export const SET_CURRENT_SETTING = "SET_CURRENT_SETTING";
export const GET_SETTINGS = "GET_SETTINGS";
export const ADD_SETTING = "ADD_SETTING";
export const EDIT_SETTING = "EDIT_SETTING";
export const DELETE_SETTING = "DELETE_SETTING";
export const SETTING_ERROR = "SETTING_ERROR";
export const CLEAR_SETTING = "CLEAR_SETTING";
export const FILTER_SETTING = "FILTER_SETTING";
export const GET_TOTAL_SETTING = "GET_TOTAL_SETTING";
export const GET_ALL_SETTINGS = "GET_ALL_SETTINGS";

export const GET_GROCERY = "GET_GROCERY";
export const SET_CURRENT_GROCERY = "SET_CURRENT_GROCERY";
export const GET_GROCERYS = "GET_GROCERYS";
export const ADD_GROCERY = "ADD_GROCERY";
export const EDIT_GROCERY = "EDIT_GROCERY";
export const DELETE_GROCERY = "DELETE_GROCERY";
export const GROCERY_ERROR = "GROCERY_ERROR";
export const CLEAR_GROCERY = "CLEAR_GROCERY";
export const FILTER_GROCERY = "FILTER_GROCERY";
export const GET_TOTAL_GROCERY = "GET_TOTAL_GROCERY";
export const GET_ALL_GROCERYS = "GET_ALL_GROCERYS";

export const GET_CITY = "GET_CITY";
export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const GET_CITIES = "GET_CITIES";
export const ADD_CITY = "ADD_CITY";
export const EDIT_CITY = "EDIT_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const CITY_ERROR = "CITY_ERROR";
export const CLEAR_CITY = "CLEAR_CITY";
export const FILTER_CITY = "FILTER_CITY";
export const GET_TOTAL_CITY = "GET_TOTAL_CITY";
export const GET_ALL_CITIES = "CITIES";
export const GET_STATES = "GET_STATES";

export const GET_AREA = "GET_AREA";
export const SET_CURRENT_AREA = "SET_CURRENT_AREA";
export const GET_AREAS = "GET_AREAS";
export const ADD_AREA = "ADD_AREA";
export const EDIT_AREA = "EDIT_AREA";
export const DELETE_AREA = "DELETE_AREA";
export const AREA_ERROR = "AREA_ERROR";
export const CLEAR_AREA = "CLEAR_AREA";
export const FILTER_AREA = "FILTER_AREA";
export const GET_TOTAL_AREA = "GET_TOTAL_AREA";
export const GET_ALL_AREAS = "GET_ALL_AREAS";
export const POPULATE_AREAS = "POPULATE_AREAS";

export const POPULATE_CITIES = "POPULATE_CITIES";

export const GET_KIT_REQ = "GET_KIT_REQ";
export const SET_CURRENT_KIT_REQ = "SET_CURRENT_KIT_REQ";
export const GET_KIT_REQS = "GET_KIT_REQS";
export const ADD_KIT_REQ = "ADD_KIT_REQ";
export const EDIT_KIT_REQ = "EDIT_KIT_REQ";
export const DELETE_KIT_REQ = "DELETE_KIT_REQ";
export const KIT_REQ_ERROR = "KIT_REQ_ERROR";
export const CLEAR_KIT_REQ = "CLEAR_KIT_REQ";
export const FILTER_KIT_REQ = "FILTER_KIT_REQ";
export const GET_TOTAL_KIT_REQ = "GET_TOTAL_KIT_REQ";
export const GET_ALL_KIT_REQS = "KIT_REQS";

export const GET_CONTACTUS = "GET_CONTACTUS";
export const SET_CURRENT_CONTACTUS = "SET_CURRENT_CONTACTUS";
export const GET_CONTACTUSS = "GET_CONTACTUSS";
export const ADD_CONTACTUS = "ADD_CONTACTUS";
export const EDIT_CONTACTUS = "EDIT_CONTACTUS";
export const DELETE_CONTACTUS = "DELETE_CONTACTUS";
export const CONTACTUS_ERROR = "CONTACTUS_ERROR";
export const CLEAR_CONTACTUS = "CLEAR_CONTACTUS";
export const FILTER_CONTACTUS = "FILTER_CONTACTUS";
export const GET_TOTAL_CONTACTUS = "GET_TOTAL_CONTACTUS";
export const GET_ALL_CONTACTUS = "GET_ALL_CONTACTUS";

export const GET_ORGANISATION = "GET_ORGANISATION";
export const SET_CURRENT_ORGANISATION = "SET_CURRENT_ORGANISATION";
export const GET_ORGANISATIONS = "GET_ORGANISATIONS";
export const ADD_ORGANISATION = "ADD_ORGANISATION";
export const EDIT_ORGANISATION = "EDIT_ORGANISATION";
export const DELETE_ORGANISATION = "DELETE_ORGANISATION";
export const ORGANISATION_ERROR = "ORGANISATION_ERROR";
export const CLEAR_ORGANISATION = "CLEAR_ORGANISATION";
export const FILTER_ORGANISATION = "FILTER_ORGANISATION";
export const GET_TOTAL_ORGANISATION = "GET_TOTAL_ORGANISATION";
export const GET_ALL_ORGANISATIONS = "GET_ALL_ORGANISATIONS";

export const GET_CAUSE = "GET_CAUSE";
export const SET_CURRENT_CAUSE = "SET_CURRENT_CAUSE";
export const GET_CAUSES = "GET_CAUSES";
export const ADD_CAUSE = "ADD_CAUSE";
export const EDIT_CAUSE = "EDIT_CAUSE";
export const DELETE_CAUSE = "DELETE_CAUSE";
export const CAUSE_ERROR = "CAUSE_ERROR";
export const CLEAR_CAUSE = "CLEAR_CAUSE";
export const FILTER_CAUSE = "FILTER_CAUSE";
export const GET_TOTAL_CAUSE = "GET_TOTAL_CAUSE";
export const GET_ALL_CAUSES = "GET_ALL_CAUSES";
